name: ci
on:
  push: { branches: [ "main" ] }
  pull_request:
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install API deps
        run: |
          cd apps/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd apps/api
          pytest -q
